Staging
F5Networks/f5-aci-servicecenter pull request #103
Opened 2021-09-14 15:17 UTC by vishwajeetgslab

Hi @JosephPJordan updated the docs for v2.9 Release. Can you please review and merge it. Let me know anything needs to changed. Thanks

2021-09-14 15:45 UTC, JosephPJordan commented on docs/l2-l3.rst
> +The default gateway is created on the BIG-IP device and is added to the application database. For an HA setup, the default gateway will automatically sync to the BIG-IP peer device. F5 ACI ServiceCen
F5 ACI ServiceCenter v2.9 added support for a brownfield default gateway, where the default gateway automatically syncs to the FASC database once the user navigates to the L2-L3 tab. FASC added support to allow any Default Gateway name to be synced to the FASC database (in previous versions, the only supported default gateway name was **apic-default-gateway**).

2021-09-14 15:58 UTC, JosephPJordan commented on docs/navigate.rst
> +   The table shows all the VLANs (vlan encaps), Self IP, Interfaces from the BIG-IP device that have a corresponding **Endpoint Group|Application Profile|Tenant** entry on the APIC. These correspond
..by clicking the dropdown icon in the Self IP and Interface columns respectively.

2021-09-14 15:59 UTC, JosephPJordan commented on docs/navigate.rst
> +2. From the :guilabel:`Partition` list, click the partition you're interested in. **All partition** partition is supported from v2.9 onwards for VIP table.
The **All partition** partition is supported for the VIP table in v2.9 and later.

2021-09-14 16:00 UTC, JosephPJordan commented on docs/navigate.rst
> +2. From the :guilabel:`Partition` list, click the partition. **All partition** partition is supported from v2.9 onwards for Node table.
The All partition partition is supported for the Node table in v2.9 and later.

2021-09-14 16:24 UTC, JosephPJordan commented on docs/navigate.rst
> +5. F5 ACI ServiceCenter supports MAC masquerade mac display under BIG-IP endpoint details on VIP visibility dashboard. MAC address type details( eg. MAC masquerade MAC or Normal MAC ) will be display
(should 'mac' in mac display be capitalized? seems like it.)
... on the VIP visibility dashboard.
MAC address type details (such as MAC masquerade or normal MAC) are displayed when you hover over the Information icon in the MAC column of the BIG-IP endpoint details table.

2021-09-14 16:26 UTC, JosephPJordan commented on docs/navigate.rst
> +6. F5 ACI ServiceCenter supports VXLAN tunnel interfaces along with individual, Port channel, Virtual port channel interfaces on Node table visibility dashboard.
....along with individual, Port channel, and Virtual port channel interfaces on the Node table visibility dashboard.

2021-09-14 16:30 UTC, JosephPJordan commented on docs/navigate.rst
> +   To view details of the VXLAN tunnel interfaces, Click on Node IP in Node information table -> Scroll down to APIC Endpoint details table. All interfaces associated with the node like VPC/PC/Indivi
... tunnel interfaces, click **Node IP** in the Node information table, and then scroll down to the APIC Endpoint details table. 

All interfaces associated with the node, such as VPC, PC, Individual, and Tunnel, are displayed in the interface column. When you click the interface, additional information related to these interfaces displays in the side panel.
(that's an attempt to fix that sentence, I really wasn't sure what '.. and On click over the interface..' meant.)

2021-09-14 16:31 UTC, JosephPJordan commented on docs/navigate.rst
> +**Q. VIP MAC masquerade Address might display old MAC on the visibility dashboard**
**Q. VIP MAC masquerade addresses might display an old MAC address on the visibility dashboard**

2021-09-14 16:33 UTC, JosephPJordan commented on docs/navigate.rst
> +Due to APIC endpoint learning and retention behavior, it takes 10-15 mins time for updated MAC details to be available on APIC endpoint tracker. Until APIC updates the MAC address, FASC visibility da
Due to the APIC endpoint learning and retention behavior, it takes 10-15 minutes for the updated MAC details to be available on the APIC endpoint tracker.
Until APIC updates the MAC address, the FASC visibility...

2021-09-14 16:34 UTC, JosephPJordan commented on docs/pre-req.rst
> +- The following BIG-IP Plugin versions that are currently supported by the F5 ACI ServiceCenter:
The following are the BIG-IP Plugin versions currently supported by the F5 ACI ServiceCenter:

2021-09-14 16:34 UTC, JosephPJordan commented on docs/release-notes.rst
> +APIC Filesystem Glusterfs takes 15 to 20 Minutes to recover when APIC cluster goes unhealthy.
..minutes... (no caps)
.. when the APIC cluster goes...

2021-09-14 16:57 UTC, JosephPJordan commented on docs/release-notes.rst
> +The user menu on the top-right corner of the F5 ACI ServiceCenter has an option for exporting F5 ACI ServiceCenter database (**Export/Import DB > Export DB**). This option does not work on APIC versi
The User menu...   ...for exporting the F5 ACI ...

2021-09-14 16:58 UTC, JosephPJordan commented on docs/release-notes.rst
> +3. Use scp, winscp or any other preferred tool to copy out the f5.db file from this location.
..to copy the f5.db file...

2021-09-14 17:00 UTC, JosephPJordan commented on docs/release-notes.rst
> +**BIG-IP version may not be displayed correctly in FASC when BIG-IP version is upgraded or downgraded.**
...when the BIG-IP version...

2021-09-14 17:01 UTC, JosephPJordan commented on docs/release-notes.rst
> +The BIG-IP version displayed on hover over the BIG-IP IP address may not be displayed correctly when BIG-IP is upgraded or downgraded.
..version when hovering over the BIG-IP

2021-09-14 17:01 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Workaround:** Log-out and re-login the BIG-IP device in the FASC application.
Log out, and re-login to the BIG-IP device...

2021-09-14 17:06 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Workaround:** Use BIG-IP admin account for F5 ACI ServiceCenter Default Gateway operations.
Use the BIG-IP admin...

2021-09-14 17:12 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Visibility table status icons render few seconds after data for scale configs.**
(just noticed the period at the end of some of these headings.  Either with or without period is probably fine, but be consistent (ie either remove or add all periods at the end)

2021-09-14 17:17 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Visibility Dashboard → BIG-IP Endpoint Details → Interface → View Logs** (for BIG-IP interfaces) displays interface logs. By default it applies the filter of interface name (for example: 1.1 or 1.2
...logs which have interface names as a substring...

2021-09-14 17:19 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Workaround**: Upload one more AS3 sample declaration to the app and then perform a :guilabel:`Delete all` operation. (Use :guilabel:`View AS3 Declaration` and click :guilabel:`Delete`.)
...one or more sample declarations...

2021-09-14 17:19 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Once all Pool Member cards are removed from template form, adding a new pool member card fails on FASC FAST templates UI**
...from the template form,

2021-09-14 17:22 UTC, JosephPJordan commented on docs/release-notes.rst
> +If user clicks on "-" sign in front on pool members card and tries to add pool member card again by clicking on "+" icon then then pool member card is not populated in template form.
If a user clicks the "-" sign in front of the pool members card....   ..again by clicking the "+" icon, then the pool member card is not...
(note the "then then" was the cause of the pipeline failure)

2021-09-14 17:22 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Workaround:** Refresh the basic subtab on L4-L7 tab
..on the L4-L7 tab.

2021-09-14 17:27 UTC, JosephPJordan commented on docs/release-notes.rst
> +**TextBox field displayed for 'Notice: Beta Test' field in 'bigip-fast-templates/microsoft adfs' and 'bigip-fast-templates/microsoft exchange' FAST templates.**
A TextBox  field is displayed for ... ...FAST template, but does not take data
(or something like that, it's odd without something about the issue in the heading)

2021-09-14 17:32 UTC, JosephPJordan commented on docs/release-notes.rst
> +AS3 applications will support either static nodes or dynamic nodes (using the **Manage Endpoint Mappings** button) but not both.
(does this need a "workaround: none" entry?  )

2021-09-14 17:35 UTC, JosephPJordan commented on docs/release-notes.rst
> +Note: Similar issues might be seen with other erronous configurations such as unsupported IPv4 formats like 1.2.3.4/24 instead of 1.2.3.4
erroneous

2021-09-14 17:36 UTC, JosephPJordan requested changes
some suggested edits and comments

2021-09-14 17:38 UTC, JosephPJordan commented
@vishwajeetgslab, note the pipeline failure will be fixed when you implement my edits, it failed due to a repeated word in the Grammar check

2021-09-15 11:24 UTC, manuwelakanade-GSLAB requested changes
@vishwajeetgslab : Requesting few changes.

2021-09-15 11:24 UTC, manuwelakanade-GSLAB commented on docs/install.rst
> +5. F5 ACI ServiceCenter v2.9 onwards supports LDAP authentication for BIG-IP login.
F5 ACI ServiceCenter (v2.9+) supports LDAP authentication for BIG-IP login. Admin LDAP users will be able to use all the features of the application.

2021-09-15 11:24 UTC, manuwelakanade-GSLAB commented on docs/navigate.rst
> +2. From the :guilabel:`Partition` list, select the partition you’re interested in. The **All partition** partition is supported for the VLAN table in v2.9 and later.
The **All partitions** option is supported for the VLAN table in v2.9 and later.

2021-09-15 11:24 UTC, manuwelakanade-GSLAB commented on docs/navigate.rst
> +2. From the :guilabel:`Partition` list, click the partition you're interested in. The **All partition** partition is supported for the VIP table in v2.9 and later.
The **All partitions** option is supported for the VIP table in v2.9 and later.

2021-09-15 11:24 UTC, manuwelakanade-GSLAB commented on docs/navigate.rst
> +2. From the :guilabel:`Partition` list, click the partition. **All partition** partition is supported for the Node table in v2.9 and later.
The **All partitions** option is supported for the Node table in v2.9 and later.

2021-09-15 11:24 UTC, manuwelakanade-GSLAB commented on docs/pre-req.rst
> +- The following are the BIG-IP Plugin versions currently supported by the F5 ACI ServiceCenter:
BIG-IP Plugin versions currently supported by the F5 ACI ServiceCenter:

2021-09-15 12:00 UTC, vishwajeetgslab commented
Hi @manuwelakanade-GSLAB @JosephPJordan Thanks for review. i have made the changes as per review comments.

@JosephPJordan Can you please merge the request. Thanks

2021-09-15 14:27 UTC, JosephPJordan approved these changes

2021-09-15 14:27 UTC, merged