Added a release note for version 2.10
F5Networks/f5-aci-servicecenter pull request #111
Opened 2022-03-14 08:06 UTC by selinaarokiaswamy-GSLAB

2022-03-14 08:08 UTC, manuwelakanade commented
Hi @JosephPJordan : Can you please review/merge this pull request. Thanks.

2022-03-14 16:08 UTC, JosephPJordan commented on docs/release-notes.rst
> +On update operation of FAST application, the FAST form displays duplicate pool member fields. These duplicate fields do not appear in the BIG-IP FAST Applications UI. This issue still exists when try
something like "When updating a FAST application..." Or "During the update operation of a FAST application, "

2022-03-14 16:08 UTC, JosephPJordan requested changes
@manuwelakanade, @selinaarokiaswamy-GSLAB, couple minor changes suggested

2022-03-16 22:57 UTC, JosephPJordan approved these changes

2022-03-16 22:57 UTC, merged