v2.11.1 Changes Staging merge
F5Networks/f5-aci-servicecenter pull request #121
Opened 2023-05-02 03:26 UTC by selinaarokiaswamy-GSLAB

2023-05-02 03:27 UTC, selinaarokiaswamy-GSLAB commented
@JosephPJordan Could you please review and merge this pull request to staging? Thanks

2023-05-02 17:08 UTC, JosephPJordan commented on docs/l4-l7.rst
> +6. Optionally, click on :guilabel:`Manage Endpoint Mappings` to configure Dynamic Endpoint Mappings for endpoint discovery, which dynamically updates endpoints in BIG-IP pools whenever endpoints get
Optionally, click :guilabel:`Manage Endpoint....
...whenever endpoints are attached or detached...

2023-05-02 17:11 UTC, JosephPJordan commented on docs/l4-l7.rst
> +5. Optionally, click :guilabel:`Manage Endpoint Mappings` to configure Dynamic Endpoint Mappings for endpoint discovery, which dynamically updates endpoints in BIG-IP pools whenever endpoints get att
... are attached or detached

2023-05-02 17:11 UTC, JosephPJordan commented on docs/l4-l7.rst
> +   - :guilabel:`Manage Endpoint Mappings` APIC VRF field is read-only and is retrieved from the APIC based on the provided info.
... information.

2023-05-02 17:11 UTC, JosephPJordan commented on docs/l4-l7.rst
> +   -  :guilabel:`Service-discovery/http template` provides endpoint discovery, which dynamically updates endpoints in BIG-IP pools whenever endpoints get attached or detached from APIC Endpoint Group
..are attached..

2023-05-02 17:12 UTC, JosephPJordan commented on docs/l4-l7.rst
> +   - :guilabel:`Service-discovery/http` template provides endpoint discovery, which dynamically updates endpoints in BIG-IP pools whenever endpoints get attached or detached from APIC Endpoint Groups
...are attached...

2023-05-02 17:13 UTC, JosephPJordan commented on docs/l4-l7.rst
> +   - BIG-IP pool names which are present in this application. Each pool should be displayed on a separate row. The pool has a hyperlink to BIG-IP UI to the same pool.
... to the BIG-IP UI...

2023-05-02 17:24 UTC, JosephPJordan commented on docs/l4-l7.rst
> +Refresh L4-L7 App Services tab
Refresh the...

2023-05-02 17:33 UTC, JosephPJordan commented on docs/release-notes.rst
> +VIP and VLAN Visibility Table does not display VRF information if the VIP is dynamically learned on the APIC.  VRF information is displayed if the VIP is defined as a static endpoint on the APIC.
The VIP and VLAN...

2023-05-02 17:33 UTC, JosephPJordan requested changes
A few minor suggested changes

2023-05-03 15:39 UTC, JosephPJordan approved these changes

2023-05-03 15:39 UTC, merged