2.11.3 staging merge
F5Networks/f5-aci-servicecenter pull request #134
Opened 2023-09-20 14:39 UTC by selinaarokiaswamy-GSLAB

2023-09-20 14:40 UTC, selinaarokiaswamy-GSLAB commented
@JosephPJordan could you please review and merge this PR to staging?

2023-09-21 17:36 UTC, JosephPJordan requested changes
One suggested change.  Sorry for the delay, was off the last couple days.

2023-09-21 17:36 UTC, JosephPJordan commented on docs/pre-req.rst
> +Note:  It is **recommended** to always install the **latest** plugin version on the BIG-IP device.
I suggest changing this to either:
- F5 recommends always installing the **latest** plugin version on the BIG-IP device.
or
- We recommend always installing the **latest** plugin version on the BIG-IP device.

2023-09-26 10:31 UTC, selinaarokiaswamy-GSLAB commented
@JosephPJordan I have included your suggestion in the Pre-requisites file. Could you please merge the changes?

2023-09-26 15:20 UTC, JosephPJordan approved these changes

2023-09-26 15:20 UTC, merged