v2.6 doc updates
F5Networks/f5-aci-servicecenter pull request #86
Opened 2020-09-10 08:21 UTC by manuwelakanade-GSLAB

v2.6 doc updates

2020-09-11 09:59 UTC, manuwelakanade-GSLAB commented
Hi @JosephPJordan : Can you please review this pull request. Thanks.

2020-09-11 18:00 UTC, JosephPJordan commented on docs/faq.rst
> +Visibility tables display only those entries from BIG-IP which have corresponding constructs on APIC. For example a VLAN from BIG-IP will only be displayed if that VLAN also belongs to some Tenant|Ap
(comma add, and one removed)
For example, a VLAN from BIG-IP will only be displayed... 
Similarly, a node will only be displayed if it exists ....

2020-09-11 18:02 UTC, JosephPJordan commented on docs/faq.rst
> +The F5 ACI ServiceCenter Visibility tables have an option to select the **Partition**. The VLAN/VIP/Node tables will only display entries from the selected partition and will not include Common parti
"entries (although the BIG-IP UI does... 
...will also show entries from the Common partition)."

2020-09-11 18:04 UTC, JosephPJordan commented on docs/install.rst
> +   - The active device will be indicated using a Green icon. The standby device will be indicated using a Yellow icon. Logged out device or any device for which failover state cannot be determined wi
... A logged out device...

2020-09-11 18:05 UTC, JosephPJordan commented on docs/navigate.rst
> +   -  Route domain entries are supported by VIP table. Nodes on the BIG-IP of the form **IP%RD** will be displayed in the VIP table (Supported in v2.6+).
supported by the VIP table.

2020-09-11 18:06 UTC, JosephPJordan commented on docs/navigate.rst
> +   -  Route domain entries are supported by Node table. Nodes on the BIG-IP of the form **IP%RD** will be displayed in the Node table (Supported in v2.6+).
supported by the Node table.

2020-09-11 18:08 UTC, JosephPJordan commented on docs/release-notes.rst
> +APIC Filesystem Glusterfs takes 15 to 20 Minutes to recover when APIC cluster goes unhealthy
..unhealthy.

2020-09-11 18:11 UTC, JosephPJordan commented on docs/release-notes.rst
> +The user menu on the top-right corner of the F5 ACI ServiceCenter has an option **Export/Import DB > Export DB**, for exporting the F5 ACI ServiceCenter database. This option does not work on APIC ve
... the F5 ACI ServiceCenter has an option for exporting the F5 ACI ServiceCenter database (**Export/Import DB > Export DB**).

2020-09-11 18:12 UTC, JosephPJordan commented on docs/release-notes.rst
> +1. Login to the APIC server via SSH
... via SSH.

2020-09-11 18:14 UTC, JosephPJordan commented on docs/release-notes.rst
> +2. cd /data2/gluster/gv0/F5Networks_F5ACIServiceCenter
2. Change directories to F5Networks_F5ACIServiceCenter: **cd /data2/gluster/gv0/F5Networks_F5ACIServiceCenter**.

2020-09-11 18:15 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Non-default docker0 configuration on APIC may affect connection to the management IP of Virtual BIG-IP**
... may affect ("the connection" or "connections") to the management...

2020-09-11 18:19 UTC, JosephPJordan commented on docs/release-notes.rst
> +Zoom In and Zoom out of Topology diagrams which open on Topology icon click in every tab (Visibility, Network Management and L4-L7 App Services) may get stuck in Internet Explorer browser. The positi
this first sentence is a little confusing, maybe something like:

"When you click the Topology icon in all tabs (Visibility, Network Management, and L4-L7 App Services), the Topology diagrams may get stuck when zooming in and out."

2020-09-11 18:20 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Visibility table fast scrolling on Mozilla firefox for scale configs may result in a blank screen**
Firefox

2020-09-11 18:20 UTC, JosephPJordan commented on docs/release-notes.rst
> +This is a known ag-grid issue on Mozilla Firefox browser: https://github.com/ag-grid/ag-grid/issues/2841
..on the Mozilla Firefox browser:

2020-09-11 18:23 UTC, JosephPJordan commented on docs/release-notes.rst
> +1. Switch tab from Visibility tab to one of the other tabs and swith back.
1. Switch tabs from the Visibility tab to one of the other tabs and then switch back.

2020-09-11 18:26 UTC, JosephPJordan commented on docs/release-notes.rst
> +When a dynamic endpoint mapping is added to an application using **Manage Endpoint Mappings**, the application gets created on the BIG-IP. If this mapping is deleted using the **RESET** button on **M
... was not found."

2020-09-11 18:27 UTC, JosephPJordan commented on docs/release-notes.rst
> +**AS3 application can either have static nodes or dynamic nodes but not both**
AS3 applications can...

2020-09-11 18:28 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Same Dynamic endpoint mappings on two separate partitions of a BIG-IP are not supported**
Using the same Dynamic endpoint mappings...

2020-09-11 18:30 UTC, JosephPJordan commented on docs/release-notes.rst
> +4. Update the members section as below to add the shareNodes property:
4. Update the members section to add the shareNodes property.  For example:

2020-09-11 18:33 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Node not removed from BIG-IP pool when node IP is a substring of some other node's IP**
"A node is not removed from a BIG-IP pool when the node IP..."
or
"Nodes are not removed from a BIG-IP pool when the node IP..."

2020-09-11 18:33 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Workaround:** Login to the BIG-IP UI and delete the problematic node
... node.

2020-09-11 18:34 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Dynamic EP discovery does not work if duplicate IP pre-exists on a different partition.**
...work if a duplicate IP address already exists on a different partition.

2020-09-11 18:36 UTC, JosephPJordan commented on docs/release-notes.rst
> +1. If BIG-IP pool members automatically get added by **Dynamic endpoint discovery** feature, but then few endpoints are deleted directly from the BIG-IP (i.e. out of band); these endpoints do not get
...added by the Dynamic...

2020-09-11 18:38 UTC, JosephPJordan commented on docs/release-notes.rst
> +2. Similarly, when few pool members are added directly to the BIG-IP (i.e. out of band), these extra members are not deleted after clicking **L4-L7 App Services --> Application Inventory --> Sync EPs
not sure what 'few pool members' means here, does this mean "when a few pool members.." ie more than a couple, but some arbitrary number?  I'd suggest either "..when a few pool members", or maybe better "when pool members are added..."

2020-09-11 18:39 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Notes              | To download Excel report for VLAN table, set the 'download' request parameter to true.                                                                    |
To download an Excel report for a VLAN table...

2020-09-11 18:39 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Notes              | To download Excel report for VIP table, set the 'download' request parameter to true.                                                                     |
To download an Excel report for a VIP..

2020-09-11 18:40 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Notes              | To download Excel report for Node table, set the 'download' request parameter to true                                                                     |
To download an Excel report for a Node...    parameter to true.

2020-09-11 18:40 UTC, JosephPJordan requested changes
@manuwelakanade-GSLAB, a few minor suggested changes

2020-09-14 06:16 UTC, manuwelakanade-GSLAB commented
Hi @JosephPJordan : Thanks for the review. I have addressed comments and updated the merge request. Can you please review/merge. Thanks.

2020-09-14 18:08 UTC, JosephPJordan approved these changes

2020-09-14 18:08 UTC, merged

2020-09-14 18:09 UTC, JosephPJordan commented
Merged, thanks!