Staging
F5Networks/f5-aci-servicecenter pull request #88
Opened 2020-09-15 13:12 UTC by manuwelakanade-GSLAB

v2.6 additional release notes

2020-09-16 08:02 UTC, manuwelakanade-GSLAB commented
Hi @JosephPJordan : Can you please review this new request with additional release notes as well. Thank you.

2020-09-16 14:56 UTC, JosephPJordan commented on docs/release-notes.rst
> +On a vCMP Host, if a user clicks the **L2-L3 Network Management > vCMP Guest** and selects a vCMP Guest and moves a few VLANs from **Selected** menu to **Available** menu and clicks **Submit**, F5 AC
...if a user clicks **L2-L3 Network Management > vCMP Guest**, selects a vCMP Guest, moves a few VLANs from the **Selected** menu to the **Available** menu, and then clicks **Submit**,

2020-09-16 14:57 UTC, JosephPJordan commented on docs/release-notes.rst
> +**If a vCMP Guest has been logged in using hostname, vCMP Guest auto-login during VLAN unassignment may result in an error**
...logged in using a hostname..

2020-09-16 14:57 UTC, JosephPJordan commented on docs/release-notes.rst
> +- Login to a vCMP Guest using hostname.
... a hostname

2020-09-16 14:59 UTC, JosephPJordan commented on docs/release-notes.rst
> +- Login to the corresponding vCMP Host and click **L2-L3 Network Management > vCMP Guest tab**.
the **L2-L3 Network Management > vCMP Guest** tab.

2020-09-16 15:02 UTC, JosephPJordan commented on docs/release-notes.rst
> +If an AS3 declaration with scale config is deleted using **L4-L7 App Services > View AS3 Declaration > Delete** button, the F5 ACI ServiceCenter may display an error  'HTTPError' object has no attrib
using the **L4-L7 App Services > View AS3 Declaration > Delete** button, 

the F5 ACI ServiceCenter may display an error stating the 'HTTPError' object has no attribute 'message'

that BIG-IP responds with, which is '503 Server Error'.

2020-09-16 15:02 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Application services declaration delete of scaled config may result in an error 'HTTPError' object has no attribute 'message'**
...an error stating the 'HTTPError' object...

2020-09-16 15:04 UTC, JosephPJordan commented on docs/release-notes.rst
> +**Workaround**: This 503 error occurs when BIG-IP is in error state or is already in the process of configuring a previous AS3 declaration. Once BIG-IP is in steady state and UI is accessible, the de
get a successful response for deleting the declaration.

2020-09-16 15:04 UTC, JosephPJordan requested changes
@manuwelakanade-GSLAB, a couple minor edits.  Thanks!

2020-09-22 14:48 UTC, manuwelakanade-GSLAB commented
Hi @JosephPJordan : I have made changes as per your review. Thanks.

2020-09-22 14:56 UTC, JosephPJordan approved these changes

2020-09-22 14:57 UTC, merged