Updated REST API doc for v2.8 release
F5Networks/f5-aci-servicecenter pull request #95
Opened 2021-05-21 14:04 UTC by KonikaChaurasiya-GSLab

Updated REST API doc for v2.8 release

2021-05-21 14:15 UTC, manuwelakanade-GSLAB commented
Hi @JosephPJordan : Can you please review and merge this pull request. This is an additional change in the REST API docs which we missed in the previous pull request. Thank you.

2021-05-21 14:41 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Notes              | This is added in the postman collection.                                                                   |
Postman 
(cap P)

2021-05-21 14:43 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Notes              | This is added in the postman collection.                                                                   |
Postman

2021-05-21 14:43 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Notes              | This is added in the postman collection .                                                                  |
Postman collection.

2021-05-21 14:44 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Title              | create/update FAST applications/partitions                                                                 |
Create

2021-05-21 14:44 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Title              | create/update FAST applications/partitions service-discovery template to support EP attach detach feature  |
Create

2021-05-21 14:44 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Notes              | This is added in the postman collection.                                                                   |
Postman

2021-05-21 14:45 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Notes              | This is added in the postman collection.                                                                   |
Postman

2021-05-21 14:47 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Title              | Searches Endpoint across login BIG-IPs                                                                     |
(not exactly sure what this means, but maybe:)
Searches Endpoints across logged in BIG-IPs
(maybe login BIG-IPs means something else, if so, leave it)

2021-05-21 14:49 UTC, JosephPJordan commented on docs/rest_api.rst
> +| Title              | Searches Endpoint for specified BIG-IP                                                                     |
Searches Endpoints (or 'the Endpoint') for the specified BIG-IP

2021-05-21 14:49 UTC, JosephPJordan requested changes
A few minor changes

2021-05-24 03:51 UTC, manuwelakanade-GSLAB commented
Hi @JosephPJordan : Thanks for the review. I've addressed all the comments and made changes accordingly. Can you please merge the pull request. Thank you.

2021-05-24 15:43 UTC, JosephPJordan approved these changes

2021-05-24 15:43 UTC, merged